on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout current
        with:
          path: current

      - uses: actions/checkout@v3
        name: Checkout current
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha }}

      - run: |
          DIFF_FILE=$(realpath diff.txt)
          cd current
          yarn
          ./src/diff.ts ./src/endpoints.d.ts ../base/src/endpoints.d.ts > $DIFF_FILE
          echo "DIFF_FILE=$DIFF_FILE" >> $GITHUB_ENV

      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('${{ env.DIFF_FILE }}','utf8').toString();

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## REST API Changes:\n```diff\n'+diff+'\n```'
            })
